<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ArrivedSoonCar extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('cars')->insert([
            [
                'car_name' => 'Nissan',
                'seats' => 15,
                'gear' => 'Automatic',
                'price' => 130,
                'car_picture' => 'front/img/cars/ToyotaHiace2025.png',
                'doors' => 3,
                'air_condition' => 1,
                'description' => 'The Toyota Hiace 2025 is a versatile van designed for both passenger transport and cargo. It seats 9 to 15 passengers and features 4 to 5 doors, including sliding side doors and rear access. Arrive Soon with both manual and automatic transmissions, it offers a choice of diesel or gasoline engines. The Hiace is known for its spacious interior, reliability, and multiple configurations, making it ideal for commercial use. Safety features include airbags and stability control, with modern amenities like a touchscreen infotainment system and ample luggage capacity.',
                'created_at' => now(),
                'updated_at' => now(),
                'plate_number' => 'A-53169',
                'make' => 'Nissan',
                'model' => 'Altima',
                'year' => 2021,
                'color' => 'White',
                'categories' => '',
                'current_location' => '',
                'status' => 'Arrive Soon',
                'expected_return_date' => null,
                'upcoming_reservation' => null,
                'latest_return_date' => null,
                'odometer' => 86,
                'chassis_number' => 'JTGHN9CP5S6028137',
                'license_expiry_date' => "2025-09-27",
                'insurance_expiry_date' => "2025-10-27",

            ],
            [
                'car_name' => 'Hyundai',
                'seats' => 15,
                'gear' => 'Automatic',
                'price' => 130,
                'car_picture' => 'front/img/cars/05.jpg',
                'doors' => 3,
                'air_condition' => 1,
                'description' => 'The Toyota Hiace 2025 is a versatile van designed for both passenger transport and cargo. It seats 9 to 15 passengers and features 4 to 5 doors, including sliding side doors and rear access. Arrive Soon with both manual and automatic transmissions, it offers a choice of diesel or gasoline engines. The Hiace is known for its spacious interior, reliability, and multiple configurations, making it ideal for commercial use. Safety features include airbags and stability control, with modern amenities like a touchscreen infotainment system and ample luggage capacity.',
                'created_at' => now(),
                'updated_at' => now(),
                'plate_number' => 'A-53169',
                'make' => 'Hyundai',
                'model' => 'Elantra',
                'year' => 2021,
                'color' => 'White',
                'categories' => '',
                'current_location' => '',
                'status' => 'Arrive Soon',
                'expected_return_date' => null,
                'upcoming_reservation' => null,
                'latest_return_date' => null,
                'odometer' => 86,
                'chassis_number' => 'JTGHN9CP5S6028137',
                'license_expiry_date' => "2025-09-27",
                'insurance_expiry_date' => "2025-10-27",

            ],
            [
                'car_name' => 'Mercedes',
                'seats' => 15,
                'gear' => 'Automatic',
                'price' => 1200,
                'car_picture' => 'front/img/cars/ToyotaHiace2025.png',
                'doors' => 3,
                'air_condition' => 1,
                'description' => 'The Toyota Hiace 2025 is a versatile van designed for both passenger transport and cargo. It seats 9 to 15 passengers and features 4 to 5 doors, including sliding side doors and rear access. Arrive Soon with both manual and automatic transmissions, it offers a choice of diesel or gasoline engines. The Hiace is known for its spacious interior, reliability, and multiple configurations, making it ideal for commercial use. Safety features include airbags and stability control, with modern amenities like a touchscreen infotainment system and ample luggage capacity.',
                'created_at' => now(),
                'updated_at' => now(),
                'plate_number' => 'A-53169',
                'make' => 'Mercedes',
                'model' => ' Benz S500',
                'year' => 2021,
                'color' => 'White',
                'categories' => '',
                'current_location' => '',
                'status' => 'Arrive Soon',
                'expected_return_date' => null,
                'upcoming_reservation' => null,
                'latest_return_date' => null,
                'odometer' => 86,
                'chassis_number' => 'JTGHN9CP5S6028137',
                'license_expiry_date' => "2025-09-27",
                'insurance_expiry_date' => "2025-10-27",

            ],
            [
                'car_name' => 'Infiniti',
                'seats' => 15,
                'gear' => 'Automatic',
                'price' => 250,
                'car_picture' => 'front/img/cars/ToyotaHiace2025.png',
                'doors' => 3,
                'air_condition' => 1,
                'description' => 'The Toyota Hiace 2025 is a versatile van designed for both passenger transport and cargo. It seats 9 to 15 passengers and features 4 to 5 doors, including sliding side doors and rear access. Arrive Soon with both manual and automatic transmissions, it offers a choice of diesel or gasoline engines. The Hiace is known for its spacious interior, reliability, and multiple configurations, making it ideal for commercial use. Safety features include airbags and stability control, with modern amenities like a touchscreen infotainment system and ample luggage capacity.',
                'created_at' => now(),
                'updated_at' => now(),
                'plate_number' => 'A-53169',
                'make' => 'Infiniti',
                'model' => 'Qx50',
                'year' => 2021,
                'color' => 'White',
                'categories' => '',
                'current_location' => '',
                'status' => 'Arrive Soon',
                'expected_return_date' => null,
                'upcoming_reservation' => null,
                'latest_return_date' => null,
                'odometer' => 86,
                'chassis_number' => 'JTGHN9CP5S6028137',
                'license_expiry_date' => "2025-09-27",
                'insurance_expiry_date' => "2025-10-27",

            ],
            [
                'car_name' => 'Land Rover',
                'seats' => 15,
                'gear' => 'Automatic',
                'price' => 900,
                'car_picture' => 'front/img/cars/ToyotaHiace2025.png',
                'doors' => 3,
                'air_condition' => 1,
                'description' => 'The Toyota Hiace 2025 is a versatile van designed for both passenger transport and cargo. It seats 9 to 15 passengers and features 4 to 5 doors, including sliding side doors and rear access. Arrive Soon with both manual and automatic transmissions, it offers a choice of diesel or gasoline engines. The Hiace is known for its spacious interior, reliability, and multiple configurations, making it ideal for commercial use. Safety features include airbags and stability control, with modern amenities like a touchscreen infotainment system and ample luggage capacity.',
                'created_at' => now(),
                'updated_at' => now(),
                'plate_number' => 'A-53169',
                'make' => 'Land Rover',
                'model' => 'Defender V4',
                'year' => 2021,
                'color' => 'White',
                'categories' => '',
                'current_location' => '',
                'status' => 'Arrive Soon',
                'expected_return_date' => null,
                'upcoming_reservation' => null,
                'latest_return_date' => null,
                'odometer' => 86,
                'chassis_number' => 'JTGHN9CP5S6028137',
                'license_expiry_date' => "2025-09-27",
                'insurance_expiry_date' => "2025-10-27",

            ],
            [
                'car_name' => 'Land Rover',
                'seats' => 15,
                'gear' => 'Automatic',
                'price' => 900,
                'car_picture' => 'front/img/cars/ToyotaHiace2025.png',
                'doors' => 3,
                'air_condition' => 1,
                'description' => 'The Toyota Hiace 2025 is a versatile van designed for both passenger transport and cargo. It seats 9 to 15 passengers and features 4 to 5 doors, including sliding side doors and rear access. Arrive Soon with both manual and automatic transmissions, it offers a choice of diesel or gasoline engines. The Hiace is known for its spacious interior, reliability, and multiple configurations, making it ideal for commercial use. Safety features include airbags and stability control, with modern amenities like a touchscreen infotainment system and ample luggage capacity.',
                'created_at' => now(),
                'updated_at' => now(),
                'plate_number' => 'A-53169',
                'make' => 'Land Rover',
                'model' => 'Defender V6',
                'year' => 2021,
                'color' => 'White',
                'categories' => '',
                'current_location' => '',
                'status' => 'Arrive Soon',
                'expected_return_date' => null,
                'upcoming_reservation' => null,
                'latest_return_date' => null,
                'odometer' => 86,
                'chassis_number' => 'JTGHN9CP5S6028137',
                'license_expiry_date' => "2025-09-27",
                'insurance_expiry_date' => "2025-10-27",

            ],
            [
                'car_name' => 'Range Rover',
                'seats' => 15,
                'gear' => 'Automatic',
                'price' => 900,
                'car_picture' => 'front/img/cars/ToyotaHiace2025.png',
                'doors' => 3,
                'air_condition' => 1,
                'description' => 'The Toyota Hiace 2025 is a versatile van designed for both passenger transport and cargo. It seats 9 to 15 passengers and features 4 to 5 doors, including sliding side doors and rear access. Arrive Soon with both manual and automatic transmissions, it offers a choice of diesel or gasoline engines. The Hiace is known for its spacious interior, reliability, and multiple configurations, making it ideal for commercial use. Safety features include airbags and stability control, with modern amenities like a touchscreen infotainment system and ample luggage capacity.',
                'created_at' => now(),
                'updated_at' => now(),
                'plate_number' => 'A-53169',
                'make' => 'Range Rover',
                'model' => 'Vogue V6',
                'year' => 2021,
                'color' => 'White',
                'categories' => '',
                'current_location' => '',
                'status' => 'Arrive Soon',
                'expected_return_date' => null,
                'upcoming_reservation' => null,
                'latest_return_date' => null,
                'odometer' => 86,
                'chassis_number' => 'JTGHN9CP5S6028137',
                'license_expiry_date' => "2025-09-27",
                'insurance_expiry_date' => "2025-10-27",

            ],
            [
                'car_name' => 'Nissan',
                'seats' => 15,
                'gear' => 'Automatic',
                'price' => 80,
                'car_picture' => 'front/img/cars/ToyotaHiace2025.png',
                'doors' => 3,
                'air_condition' => 1,
                'description' => 'The Toyota Hiace 2025 is a versatile van designed for both passenger transport and cargo. It seats 9 to 15 passengers and features 4 to 5 doors, including sliding side doors and rear access. Arrive Soon with both manual and automatic transmissions, it offers a choice of diesel or gasoline engines. The Hiace is known for its spacious interior, reliability, and multiple configurations, making it ideal for commercial use. Safety features include airbags and stability control, with modern amenities like a touchscreen infotainment system and ample luggage capacity.',
                'created_at' => now(),
                'updated_at' => now(),
                'plate_number' => 'A-53169',
                'make' => 'Nissan',
                'model' => 'Versa',
                'year' => 2021,
                'color' => 'White',
                'categories' => '',
                'current_location' => '',
                'status' => 'Arrive Soon',
                'expected_return_date' => null,
                'upcoming_reservation' => null,
                'latest_return_date' => null,
                'odometer' => 86,
                'chassis_number' => 'JTGHN9CP5S6028137',
                'license_expiry_date' => "2025-09-27",
                'insurance_expiry_date' => "2025-10-27",

            ],
           
        ]);
    }
}
