<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CarsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // You can add more entries as needed
        DB::table('cars')->insert([
            [
                'car_name' => 'Toyota',
                'seats' => 15,
                'gear' => 'Automatic',
                'price' => 400,
                'car_picture' => 'front/img/cars/ToyotaHiace2025.png',
                'doors' => 3,
                'air_condition' => 1,
                'description' => 'The Toyota Hiace 2025 is a versatile van designed for both passenger transport and cargo. It seats 9 to 15 passengers and features 4 to 5 doors, including sliding side doors and rear access. Available with both manual and automatic transmissions, it offers a choice of diesel or gasoline engines. The Hiace is known for its spacious interior, reliability, and multiple configurations, making it ideal for commercial use. Safety features include airbags and stability control, with modern amenities like a touchscreen infotainment system and ample luggage capacity.',
                'created_at' => now(),
                'updated_at' => now(),
                'plate_number' => 'A-53169',
                'make' => 'Toyota',
                'model' => 'Hiace',
                'year' => 2025,
                'color' => 'White',
                'categories' => '',
                'current_location' => '',
                'status' => 'Available',
                'expected_return_date' => null,
                'upcoming_reservation' => null,
                'latest_return_date' => null,
                'odometer' => 86,
                'chassis_number' => 'JTGHN9CP5S6028137',
                'license_expiry_date' => "2025-09-27",
                'insurance_expiry_date' => "2025-10-27",

            ],

            [
                'car_name' => 'Infiniti',
                'seats' => 5,
                'gear' => 'Automatic',
                'price' => 250,
                'car_picture' => 'front/img/cars/InfinitiQX502021.png',
                'doors' => 5,
                'air_condition' => 1,
                'description' => 'The Infiniti QX50 2021 is a luxury compact SUV with seating for 5 passengers and a spacious cargo area capable of holding 7 to 9 bags. It features 5 doors, including a rear liftgate for easy access to the luggage area. Known for its elegant design, advanced technology, and comfortable ride, the QX50 blends performance with luxury, making it ideal for families and daily commuting.',
                'created_at' => now(),
                'updated_at' => now(),
                'plate_number' => 'A-52203',
                'make' => 'Infiniti',
                'model' => 'QX50', // 
                'year' => 2021,  //
                'color' => 'Dark Gray',
                'categories' => 'Luxury, SUV',
                'current_location' => 'Main Parking',
                'status' => 'available', //
                'expected_return_date' => null,
                'upcoming_reservation' => null,
                'latest_return_date' => null, 
                'odometer' => 13322,
                'chassis_number' => '3PCAJ5BB1MF108423',
                'license_expiry_date' => '2025-10-07',
                'insurance_expiry_date' => '2025-11-07',
            ],
            [
                'car_name' => 'Honda',
                'seats' => 7-8,
                'gear' => 'Automatic',
                'price' => 250,
                'car_picture' => 'public/front/img/cars/HondaOdyssey2020_1.png',
                'doors' => 5,
                'air_condition' => 1,
                'description' => 'The Honda Odyssey 2020 is a family-friendly minivan offering seating for 7 to 8 passengers and a flexible cargo area that can fit 5 to 6 bags with all seats in use. It has 5 doors, including sliding doors for easy access and a rear liftgate for loading luggage. The Odyssey is known for its comfort, advanced safety features, and spacious interior, making it a popular choice for families and long road trips.',
                'created_at' => now(),
                'updated_at' => now(),
                'plate_number' => 'A-52271',
                'make' => 'Honda',
                'model' => 'Odyssey',
                'year' => 2020,
                'color' => 'Gray',
                'categories' => '',
                'current_location' => 'Main Parking',
                'status' => 'available', //
                'expected_return_date' => null,
                'upcoming_reservation' => null, //
                'latest_return_date' => '2024-10-11 14:07:28',
                'odometer' => 126982,
                'chassis_number' => '5FNRL6H55LB049850',
                'license_expiry_date' => '2025-09-22',
                'insurance_expiry_date' => '2025-10-22',
            ],

            [
                'car_name' => 'Nissan',
                'seats' => 5,
                'gear' => 'Automatic',
                'price' => 70,
                'car_picture' => 'path/to/toyota_camry.jpg',
                'doors' => 4,
                'air_condition' => 1,
                'description' => 'The Nissan Sunny 2020 is a compact sedan designed for practicality and comfort, featuring 5 seats and a trunk that holds 3 to 4 bags. With 4 doors, including spacious rear access, it offers a comfortable ride for both drivers and passengers. Known for its fuel efficiency and reliability, the Sunny is an excellent choice for urban commuting and everyday use.',
                'created_at' => now(),
                'updated_at' => now(),
                'plate_number' => 'B-48806',
                'make' => 'Nissan',
                'model' => 'Sunny',
                'year' => 2020,
                'color' => 'White',
                'categories' => '',
                'current_location' => '',
                'status' => 'booked',
                'expected_return_date' => "2024-10-27 21:00",
                'upcoming_reservation' => null, //
                'latest_return_date' => '2024-10-11 14:07:28',
                'odometer' => 82561,
                'chassis_number' => 'MDHBN7AD7LG722534',
                'license_expiry_date' => '2025-09-22',
                'insurance_expiry_date' => '2025-10-22',
            ],
            [
                'car_name' => 'Hyundai',
                'seats' => 5,
                'gear' => 'Automatic',
                'price' => 120,
                'car_picture' => 'path/to/toyota_camry.jpg',
                'doors' => 4,
                'air_condition' => 1,
                'description' => 'The Hyundai Sonata 2021 is a stylish midsize sedan that offers 5 seats and a spacious trunk capable of holding 4 to 5 bags. With its 4-door configuration, the Sonata provides easy access for passengers and their belongings. Known for its sleek design, advanced technology features, and a comfortable ride, the Sonata is an excellent choice for those seeking a reliable and modern vehicle for daily commuting and long drives.',
                'created_at' => now(),
                'updated_at' => now(),
                'plate_number' => 'B-69415',
                'make' => 'Hyundai',
                'model' => 'Sonata',
                'year' => 2021,
                'color' => 'Gray',
                'categories' => '',
                'current_location' => '',
                'status' => 'booked',
                'expected_return_date' => "2024-11-02 19:00",
                'upcoming_reservation' => null,
                'latest_return_date' => null,
                'odometer' => 54147,
                'chassis_number' => 'KMHL64JA9MA165650',
                'license_expiry_date' => '2025-09-22',
                'insurance_expiry_date' => '2025-10-22',
            ],

            [
                'car_name' => 'Hyundai',
                'seats' => 5,
                'gear' => 'Automatic',
                'price' => 200,
                'car_picture' => 'path/to/toyota_camry.jpg',
                'doors' => 5,
                'air_condition' => 1,
                'description' => 'The Hyundai Santa Fe 2023 is a versatile midsize SUV offering 5 seats and a generous cargo space that can hold 4 to 5 bags. With its 5-door design, including a rear liftgate for easy access to the cargo area, the Santa Fe combines practicality with a modern aesthetic. Known for its comfortable interior, advanced safety features, and a smooth ride, the Santa Fe is an excellent option for families and adventure seekers alike.',
                'created_at' => now(),
                'updated_at' => now(),
                'plate_number' => 'A-50943',
                'make' => 'Hyundai',
                'model' => 'Santa Fe',
                'year' => 2023,
                'color' => 'Black',
                'categories' => '',
                'current_location' => '',
                'status' => 'booked',
                'expected_return_date' => "2024-10-31 12:00",
                'upcoming_reservation' => null,
                'latest_return_date' => null,
                'odometer' => 13696,
                'chassis_number' => '5NMS5DAL6PH501348',
                'license_expiry_date' => '2025-09-22',
                'insurance_expiry_date' => '2025-10-22',
            ],
            [
                'car_name' => 'Mitsubishi',
                'seats' => 7,
                'gear' => 'Automatic',
                'price' => 200,
                'car_picture' => 'path/to/toyota_camry.jpg',
                'doors' => 5,
                'air_condition' => 1,
                'description' => 'The Mitsubishi Outlander 2024 is a family-friendly midsize SUV that offers 7 seats and a flexible cargo area suitable for 3 to 4 bags with all seats in use. Its 5-door configuration, including a rear liftgate, provides easy access for passengers and cargo. Known for its spacious interior, advanced safety technology, and off-road capabilities, the Outlander is an excellent choice for families and outdoor enthusiasts looking for a reliable and versatile vehicle.',
                'created_at' => now(),
                'updated_at' => now(),
                'plate_number' => 'A-52240',
                'make' => 'Mitsubishi',
                'model' => 'Outlander',
                'year' => 2024,
                'color' => 'Red',
                'categories' => '',
                'current_location' => '',
                'status' => 'booked',
                'expected_return_date' => "2024-11-07 15:00",
                'upcoming_reservation' => null,
                'latest_return_date' => null,
                'odometer' => 17255,
                'chassis_number' => 'JA4J4VA85RZ010990',
                'license_expiry_date' => '2025-09-27',
                'insurance_expiry_date' => '2025-10-27',
            ],
            [
                'car_name' => 'BMW',
                'seats' => 4,
                'gear' => 'Automatic',
                'price' => 220,
                'car_picture' => 'path/to/toyota_camry.jpg',
                'doors' => 2,
                'air_condition' => 1,
                'description' => 'The BMW 228i 2021 is a stylish and sporty coupe that offers 4 seats and a trunk capacity of 2 to 3 bags, making it suitable for short trips and weekend getaways. With its 2-door design, the 228i combines performance and luxury, featuring a powerful engine, agile handling, and a well-appointed interior. Known for its dynamic driving experience and premium features, the 228i is an excellent choice for enthusiasts looking for a compact luxury coupe.',
                'created_at' => now(),
                'updated_at' => now(),
                'plate_number' => 'A-52270',
                'make' => 'BMW',
                'model' => '228i',
                'year' => 2021,
                'color' => 'Black',
                'categories' => '',
                'current_location' => '',
                'status' => 'booked',
                'expected_return_date' => "2024-10-08 18:30",
                'upcoming_reservation' => null,
                'latest_return_date' => null,
                'odometer' => 72355,
                'chassis_number' => 'WBA53AK03M7J02001',
                'license_expiry_date' => '2025-09-22',
                'insurance_expiry_date' => '2025-10-22',
            ],
            [
                'car_name' => 'Kia',
                'seats' => 5,
                'gear' => 'Automatic',
                'price' => 85,
                'car_picture' => 'path/to/toyota_camry.jpg',
                'doors' => 4,
                'air_condition' => 1,
                'description' => 'The Kia Cerato 2020 is a compact sedan that offers 5 seats and a trunk space capable of holding 3 to 4 bags, making it a practical choice for everyday use. With its 4-door configuration, the Cerato provides easy access for passengers and their belongings. Known for its stylish design, reliable performance, and a range of modern features, the Cerato is an excellent option for those seeking a well-rounded and affordable sedan for urban commuting and family trips.',
                'created_at' => now(),
                'updated_at' => now(),
                'plate_number' => 'A-58379',
                'make' => 'Kia',
                'model' => 'Cerato',
                'year' => 2020,
                'color' => 'Gray',
                'categories' => '',
                'current_location' => 'Main Parking',
                'status' => 'booked',
                'expected_return_date' => "2024-10-31 18:30",
                'upcoming_reservation' => null, //
                'latest_return_date' => '2024-10-09 20:14:28',
                'odometer' => 142316,
                'chassis_number' => 'KNAF24169L5863981',
                'license_expiry_date' => null,
                'insurance_expiry_date' => null,
            ],
            [
                'car_name' => 'Kia',
                'seats' => 5,
                'gear' => 'Automatic',
                'price' => 85,
                'car_picture' => 'path/to/toyota_camry.jpg',
                'doors' => 4,
                'air_condition' => 1,
                'description' => 'The Kia Cerato 2020 is a compact sedan that offers 5 seats and a trunk space capable of holding 3 to 4 bags, making it a practical choice for everyday use. With its 4-door configuration, the Cerato provides easy access for passengers and their belongings. Known for its stylish design, reliable performance, and a range of modern features, the Cerato is an excellent option for those seeking a well-rounded and affordable sedan for urban commuting and family trips.',
                'created_at' => now(),
                'updated_at' => now(),
                'plate_number' => 'A-58378',
                'make' => 'Kia',
                'model' => 'Cerato',
                'year' => 2020,
                'color' => 'Blue',
                'categories' => '',
                'current_location' => 'Main Parking',
                'status' => 'booked',
                'expected_return_date' => "2024-11-04 19:00",
                'upcoming_reservation' => null,
                'latest_return_date' => '2024-10-09 21:05:23',
                'odometer' => 149781,
                'chassis_number' => 'KNAF24167L5867009',
                'license_expiry_date' => "2025-06-23",
                'insurance_expiry_date' => "2025-07-23",
            ],
            [
                'car_name' => 'Hyundai',
                'seats' => 5,
                'gear' => 'Automatic',
                'price' => 100,
                'car_picture' => 'path/to/toyota_camry.jpg',
                'doors' => 5,
                'air_condition' => 1,
                'description' => 'The Hyundai Venue 2021 is a compact SUV designed for urban driving, offering 5 seats and a versatile cargo area that can fit 2 to 3 bags. With its 5-door layout, including a rear liftgate for easy access to the trunk, the Venue is practical for daily use. Known for its stylish design, advanced technology features, and efficient performance, the Venue is an excellent choice for those seeking a small, maneuverable SUV that is perfect for city living.',
                'created_at' => now(),
                'updated_at' => now(),
                'plate_number' => 'A-53169',
                'make' => 'Hyundai',
                'model' => 'Venue',
                'year' => 2021,
                'color' => 'Silver',
                'categories' => '',
                'current_location' => 'Main Parking',
                'status' => 'booked',
                'expected_return_date' => "2027-04-01 12:30",
                'upcoming_reservation' => null,
                'latest_return_date' => '2024-10-12 19:23:50',
                'odometer' => 22811,
                'chassis_number' => 'KMHRC8A39MU079121',
                'license_expiry_date' => "2025-09-22",
                'insurance_expiry_date' => "2025-10-22",
            ],
            // Add more car entries here
        ]);
    }
}
