<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Car;
class CarsTableSeeder extends Seeder
{
    public function run()
    {
        $cars = [
            [
                'node_id' => '22-12',
                'car_name' => 'Toyota',
                'seats' => 15, 
                'gear' => 'Automatic',
                'price_daily' => 400,
                'price_weekly' => 2400,
                'price_monthly' => 8000,
                'car_picture' => 'front/img/cars/hiece/20241001_155838.jpg',
                'doors' => 4,
                'description' => 'The Toyota Hiace 2025 is a versatile van designed for both passenger transport and cargo. It seats 9 to 15 passengers and features 4 to 5 doors, including sliding side doors and rear access. Available with both manual and automatic transmissions, it offers a choice of diesel or gasoline engines. The Hiace is known for its spacious interior, reliability, and multiple configurations, making it ideal for commercial use. Safety features include airbags and stability control, with modern amenities like a touchscreen infotainment system and ample luggage capacity.',
                'created_at' => now(),
                'updated_at' => now(),
                'plate_number' => 'B-78694',
                'make' => 'Toyota',
                'model' => 'Hiace',
                'year' => 2025,
                'color' => 'White',
                'categories' => 'null',
                'status' => 'available',
                'expected_return_date' => null,
                'upcoming_reservation' => null,
                'chassis_number' => 'JTGHN9CP5S6028137'
            ],
            [
                'node_id' => '159-13',
                'car_name' => 'Infiniti',
                'seats' => 5,
                'gear' => 'Automatic',
                'price_daily' => 250,
                'price_weekly' => 1450,
                'price_monthly' => 5000,
                'car_picture' => 'front/img/model.png',
                'doors' => 5,
                'description' => 'The Infiniti QX50 2021 is a luxury compact SUV with seating for 5 passengers and a spacious cargo area capable of holding 7 to 9 bags. It features 5 doors, including a rear liftgate for easy access to the luggage area. Known for its elegant design, advanced technology, and comfortable ride, the QX50 blends performance with luxury, making it ideal for families and daily commuting.',
                'created_at' => now(),
                'updated_at' => now(),
                'plate_number' => 'A-52203',
                'make' => 'Infiniti',
                'model' => 'QX50',
                'year' => 2021,
                'color' => 'Dark Gray',
                'categories' => 'Compact',
                'status' => 'Available',
                'expected_return_date' => null,
                'upcoming_reservation' => null,
                'chassis_number' => '3PCAJ5BB1MF108423'
            ],
            [
                'node_id' => '17-7',
                'car_name' => 'Honda',
                'seats' => 8,
                'gear' => 'Automatic',
                'price_daily' => 250,
                'price_weekly' => 1500,
                'price_monthly' => 4500,
                'car_picture' => 'front/img/cars/honda_odyssey/20241001_153820.jpg',
                'doors' => 5,
                'description' => 'The Honda Odyssey 2020 is a family-friendly minivan offering seating for 7 to 8 passengers and a flexible cargo area that can fit 5 to 6 bags with all seats in use. It has 5 doors, including sliding doors for easy access and a rear liftgate for loading luggage. The Odyssey is known for its comfort, advanced safety features, and spacious interior, making it a popular choice for families and long road trips.',
                'created_at' => now(),
                'updated_at' => now(),
                'plate_number' => 'A-52271',
                'make' => 'Honda',
                'model' => 'Odyssey',
                'year' => 2020,
                'color' => 'Gray',
                'categories' => 'null',
                'status' => 'Available',
                'expected_return_date' => null,
                'upcoming_reservation' => null,
                'chassis_number' => '5FNRL6H55LB049850'
            ],
            [
                'node_id' => '15-5',
                'car_name' => 'Nissan',
                'seats' => 5,
                'gear' => 'Automatic',
                'price_daily' => 70,
                'price_weekly' => 420,
                'price_monthly' => 1400,
                'car_picture' => 'front/img/model.png',
                'doors' => 5,
                'description' => 'The Nissan Sunny 2020 is a compact sedan designed for practicality and comfort, featuring 5 seats and a trunk that holds 3 to 4 bags. With 4 doors, including spacious rear access, it offers a comfortable ride for both drivers and passengers. Known for its fuel efficiency and reliability, the Sunny is an excellent choice for urban commuting and everyday use.',
                'created_at' => now(),
                'updated_at' => now(),
                'plate_number' => 'B-48806',
                'make' => 'Nissan',
                'model' => 'Sunny',
                'year' => 2020,
                'color' => 'White',
                'categories' => 'Electric',
                'status' => 'Available',
                'expected_return_date' => null,
                'upcoming_reservation' => null,
                'chassis_number' => 'MDHBN7AD7LG722534'
            ],
            [
                'node_id' => '18-8',
                'car_name' => 'Hyundai',
                'seats' => 5,
                'gear' => 'Automatic',
                'price_daily' => 120,
                'price_weekly' => 720,
                'price_monthly' => 2800,
                'car_picture' => 'front/img/cars/sonata/20241001_154129.jpg',
                'doors' => 5,
                'description' => 'The Hyundai Sonata 2021 is a stylish midsize sedan that offers 5 seats and a spacious trunk capable of holding 4 to 5 bags. With its 4-door configuration, the Sonata provides easy access for passengers and their belongings. Known for its sleek design, advanced technology features, and a comfortable ride, the Sonata is an excellent choice for those seeking a reliable and modern vehicle for daily commuting and long drives.',
                'created_at' => now(),
                'updated_at' => now(),
                'plate_number' => 'B-69415',
                'make' => 'Hyundai',
                'model' => 'Sonata',
                'year' => 2021,
                'color' => 'Gray',
                'categories' => 'Sedan',
                'status' => 'Available',
                'expected_return_date' => null,
                'upcoming_reservation' => null,
                'chassis_number' => 'KMHL64JA9MA165650'
            ],
            [
                'node_id' => '18-8',
                'car_name' => 'Hyundai',
                'seats' => 5,
                'gear' => 'Automatic',
                'price_daily' => 200,
                'price_weekly' => 1200,
                'price_monthly' => 4200,
                'car_picture' => 'front/img/model.png',
                'doors' => 5,
                'description' => 'The Hyundai Santa Fe 2023 is a versatile midsize SUV offering 5 seats and a generous cargo space that can hold 4 to 5 bags. With its 5-door design, including a rear liftgate for easy access to the cargo area, the Santa Fe combines practicality with a modern aesthetic. Known for its comfortable interior, advanced safety features, and a smooth ride, the Santa Fe is an excellent option for families and adventure seekers alike.',
                'created_at' => now(),
                'updated_at' => now(),
                'plate_number' => 'A-50943',
                'make' => 'Hyundai',
                'model' => 'Santa Fe',
                'year' => 2023,
                'color' => 'Black',
                'categories' => 'Sedan',
                'status' => 'Available',
                'expected_return_date' => null,
                'upcoming_reservation' => null,
                'chassis_number' => '5NMS5DAL6PH501348'
            ],
            [
                'node_id' => '20-10',
                'car_name' => 'Mitsubishi',
                'seats' => 7,
                'gear' => 'Automatic',
                'price_daily' => 200,
                'price_weekly' => 1200,
                'price_monthly' => 4200,
                'car_picture' => 'front/img/cars/mitsubishi/20241002_171018.jpg',
                'doors' => 5,
                'description' => 'The Hyundai Santa Fe 2023 is a versatile midsize SUV offering 5 seats and a generous cargo space that can hold 4 to 5 bags. With its 5-door design, including a rear liftgate for easy access to the cargo area, the Santa Fe combines practicality with a modern aesthetic. Known for its comfortable interior, advanced safety features, and a smooth ride, the Santa Fe is an excellent option for families and adventure seekers alike.',
                'created_at' => now(),
                'updated_at' => now(),
                'plate_number' => 'A-50943',
                'make' => 'Mitsubishi',
                'model' => 'Outlander',
                'year' => 2024,
                'color' => 'Red',
                'categories' => 'Sedan',
                'status' => 'Available',
                'expected_return_date' => null,
                'upcoming_reservation' => null,
                'chassis_number' => 'JA4J4VA85RZ010990'
            ],
            [
                'node_id' => '21-11',
                'car_name' => 'BMW',
                'seats' => 4,
                'gear' => 'Automatic',
                'price_daily' => 220,
                'price_weekly' => 1300,
                'price_monthly' => 4000,
                'car_picture' => 'front/img/cars/bmw 228i/WhatsApp Image 2024-10-17 at 9.36.56 AM.jpeg',
                'doors' => 2,
                'description' => 'The BMW 228i 2021 is a stylish and sporty coupe that offers 4 seats and a trunk capacity of 2 to 3 bags, making it suitable for short trips and weekend getaways. With its 2-door design, the 228i combines performance and luxury, featuring a powerful engine, agile handling, and a well-appointed interior. Known for its dynamic driving experience and premium features, the 228i is an excellent choice for enthusiasts looking for a compact luxury coupe.',
                'created_at' => now(),
                'updated_at' => now(),
                'plate_number' => 'A-52270',
                'make' => 'BMW',
                'model' => '228i',
                'year' => 2021,
                'color' => 'Black',
                'categories' => 'Sedan',
                'status' => 'Available',
                'expected_return_date' => null,
                'upcoming_reservation' => null,
                'chassis_number' => 'WBA53AK03M7J02001'
            ],
            [
                'node_id' => '13-3',
                'car_name' => 'Kia',
                'seats' => 5,
                'gear' => 'Automatic',
                'price_daily' => 85,
                'price_weekly' => 500,
                'price_monthly' => 1850,
                'car_picture' => 'front/img/model.png',
                'doors' => 4,
                'description' => 'The Kia Cerato 2020 is a compact sedan that offers 5 seats and a trunk space capable of holding 3 to 4 bags, making it a practical choice for everyday use. With its 4-door configuration, the Cerato provides easy access for passengers and their belongings. Known for its stylish design, reliable performance, and a range of modern features, the Cerato is an excellent option for those seeking a well-rounded and affordable sedan for urban commuting and family trips.',
                'created_at' => now(),
                'updated_at' => now(),
                'plate_number' => 'A-58379',
                'make' => 'Kia',
                'model' => 'Cerato',
                'year' => 2020,
                'color' => 'Gray',
                'categories' => 'Sedan',
                'status' => 'Available',
                'expected_return_date' => null,
                'upcoming_reservation' => null,
                'chassis_number' => 'KNAF24169L5863981'
            ],
            [
                'node_id' => '13-3',
                'car_name' => 'Kia',
                'seats' => 5,
                'gear' => 'Automatic',
                'price_daily' => 85,
                'price_weekly' => 500,
                'price_monthly' => 1850,
                'car_picture' => 'front/img/model.png',
                'doors' => 4,
                'description' => 'The Kia Cerato 2020 is a compact sedan that offers 5 seats and a trunk space capable of holding 3 to 4 bags, making it a practical choice for everyday use. With its 4-door configuration, the Cerato provides easy access for passengers and their belongings. Known for its stylish design, reliable performance, and a range of modern features, the Cerato is an excellent option for those seeking a well-rounded and affordable sedan for urban commuting and family trips.',
                'created_at' => now(),
                'updated_at' => now(),
                'plate_number' => 'A-50943',
                'make' => 'Kia',
                'model' => 'Cerato',
                'year' => 2020,
                'color' => 'Gray',
                'categories' => 'Sedan',
                'status' => 'Available',
                'expected_return_date' => null,
                'upcoming_reservation' => null,
                'chassis_number' => 'KNAF24169L5863981'
            ],
            [
                'node_id' => '16-6',
                'car_name' => 'Hyundai',
                'seats' => 5,
                'gear' => 'Automatic',
                'price_daily' => 100,
                'price_weekly' => 595,
                'price_monthly' => 2000,
                'car_picture' => 'front/img/cars/Venue/20241001_160206.jpg',
                'doors' => 5,
                'description' => 'The Hyundai Venue 2021 is a compact SUV designed for urban driving, offering 5 seats and a versatile cargo area that can fit 2 to 3 bags. With its 5-door layout, including a rear liftgate for easy access to the trunk, the Venue is practical for daily use. Known for its stylish design, advanced technology features, and efficient performance, the Venue is an excellent choice for those seeking a small, maneuverable SUV that is perfect for city living.',
                'created_at' => now(),
                'updated_at' => now(),
                'plate_number' => 'A-53169',
                'make' => 'Hyundai',
                'model' => 'Venue',
                'year' => 2021,
                'color' => 'Silver',
                'categories' => 'Sedan',
                'status' => 'Available',
                'expected_return_date' => null,
                'upcoming_reservation' => null,
                'chassis_number' => 'KMHRC8A39MU079121'
            ],
            [
                'node_id' => '0-1',
                'car_name' => 'Nissan',
                'seats' => 5,
                'gear' => 'Automatic',
                'price_daily' => 130,
                'price_weekly' => 750,
                'price_monthly' => 2800,
                'car_picture' => 'front/img/model.png',
                'doors' => 5,
                'description' => 'The 2022 Nissan Altima is a stylish midsize sedan that seats 5 passengers. It offers a comfortable interior, advanced safety features, and two engine options: a 2.5-liter 4-cylinder for efficiency and an optional 2.0-liter turbo for added performance. With available all-wheel drive, an 8-inch touchscreen, Apple CarPlay, and Android Auto, it combines modern tech with a smooth, confident ride.',
                'created_at' => now(),
                'updated_at' => now(),
                'plate_number' => '100000',
                'make' => 'Nissan',
                'model' => 'Altima',
                'year' => 2022,
                'color' => 'Silver',
                'categories' => 'Sedan',
                'status' => 'Available',
                'expected_return_date' => null,
                'upcoming_reservation' => null,
                'chassis_number' => '00000000000000000'
            ],
            [
                'node_id' => '0-2',
                'car_name' => 'Hyundai',
                'seats' => 5,
                'gear' => 'Automatic',
                'price_daily' => 130,
                'price_weekly' => 750,
                'price_monthly' => 2800,
                'car_picture' => 'front/img/model.png',
                'doors' => 5,
                'description' => 'The 2022 Hyundai Elantra is a compact sedan that seats 5 passengers. It features a bold design, a comfortable interior, and advanced tech like an 8-inch touchscreen with Apple CarPlay and Android Auto. Known for its fuel efficiency, the Elantra offers a smooth ride with modern safety features, making it a reliable and stylish daily driver.',
                'created_at' => now(),
                'updated_at' => now(),
                'plate_number' => '200000',
                'make' => 'Hyundai',
                'model' => 'Elantra',
                'year' => 2022,
                'color' => 'Silver',
                'categories' => 'Sedan',
                'status' => 'Available',
                'expected_return_date' => null,
                'upcoming_reservation' => null,
                'chassis_number' => '00000000000000000'
            ],
            [
                'node_id' => '0-3',
                'car_name' => 'Mercedes',
                'seats' => 5,
                'gear' => 'Automatic',
                'price_daily' => 1200,
                'price_weekly' => 7200,
                'price_monthly' => 23000,
                'car_picture' => 'front/img/model.png',
                'doors' => 5,
                'description' => 'The 2022 Mercedes-Benz S500 is a luxury sedan that seats 5 passengers. It combines opulence with advanced technology, featuring a plush, spacious interior with premium materials and cutting-edge features like a 12.8-inch OLED touchscreen, a digital instrument cluster, and a Burmester 3D sound system. Powered by a 3.0-liter turbocharged inline-6 engine with EQ Boost, it delivers 429 horsepower and smooth, dynamic performance. The S500 also offers advanced safety systems and driver assistance features, making it a top choice for luxury, comfort, and technology in a sedan.',
                'created_at' => now(),
                'updated_at' => now(),
                'plate_number' => '300000',
                'make' => 'Mercedes',
                'model' => 'Benz S500',
                'year' => 2022,
                'color' => 'Silver',
                'categories' => 'Sedan',
                'status' => 'Available',
                'expected_return_date' => null,
                'upcoming_reservation' => null,
                'chassis_number' => '00000000000000000'
            ],
            [
                'node_id' => '0-4',
                'car_name' => 'Infiniti',
                'seats' => 5,
                'gear' => 'Automatic',
                'price_daily' => 250,
                'price_weekly' => 1450,
                'price_monthly' => 5000,
                'car_picture' => 'front/img/model.png',
                'doors' => 5,
                'description' => 'The 2021 Infiniti QX50 seats 5 passengers. It offers a stylish, comfortable interior with two rows of spacious seating, making it a great choice for small families or individuals seeking luxury. Powered by a 2.0-liter VC-Turbo engine, it delivers a balance of performance and fuel efficiency. The QX50 also comes with advanced technology like ProPILOT Assist, a 9-inch infotainment system, Apple CarPlay, and Android Auto, providing a blend of comfort, safety, and modern convenience.',
                'created_at' => now(),
                'updated_at' => now(),
                'plate_number' => '400000',
                'make' => 'Infiniti',
                'model' => 'Qx50',
                'year' => 2021,
                'color' => 'Silver',
                'categories' => 'Sedan',
                'status' => 'Available',
                'expected_return_date' => null,
                'upcoming_reservation' => null,
                'chassis_number' => '00000000000000000'
            ],
            [
                'node_id' => '0-5',
                'car_name' => 'Land Rover',
                'seats' => 5,
                'gear' => 'Automatic',
                'price_daily' => 900,
                'price_weekly' => 5000,
                'price_monthly' => 19000,
                'car_picture' => 'front/img/model.png',
                'doors' => 5,
                'description' => 'The 2021 Infiniti QX50 seThe 2024 Land Rover Defender V4 seats 5 to 7 passengers, depending on the configuration. This rugged SUV offers exceptional off-road capability while maintaining a refined and luxurious interior. It comes with a powerful turbocharged 2.0-liter inline-4 engine, providing strong performance both on and off the road. Inside, it features modern technology, including a large touchscreen infotainment system with Apple CarPlay, Android Auto, and advanced driver assistance systems. Known for its versatility, the Defender combines adventure-ready durability with premium comfort and style.',
                'created_at' => now(),
                'updated_at' => now(),
                'plate_number' => '500000',
                'make' => 'Land Rover',
                'model' => 'Defender V4',
                'year' => 2024,
                'color' => 'Silver',
                'categories' => 'Sedan',
                'status' => 'Available',
                'expected_return_date' => null,
                'upcoming_reservation' => null,
                'chassis_number' => '00000000000000000'
            ],
            [
                'node_id' => '0-6',
                'car_name' => 'Land Rover',
                'seats' => 5,
                'gear' => 'Automatic',
                'price_daily' => 900,
                'price_weekly' => 5000,
                'price_monthly' => 19000,
                'car_picture' => 'front/img/model.png',
                'doors' => 5,
                'description' => 'The 2024 Land Rover Defender V4 seats 5 to 7 passengers, depending on the configuration. This rugged SUV offers exceptional off-road capability while maintaining a refined and luxurious interior. It comes with a powerful turbocharged 2.0-liter inline-4 engine, providing strong performance both on and off the road. Inside, it features modern technology, including a large touchscreen infotainment system with Apple CarPlay, Android Auto, and advanced driver assistance systems. Known for its versatility, the Defender combines adventure-ready durability with premium comfort and style.',
                'created_at' => now(),
                'updated_at' => now(),
                'plate_number' => '600000',
                'make' => 'Land Rover',
                'model' => 'Defender V6',
                'year' => 2022,
                'color' => 'Silver',
                'categories' => 'Sedan',
                'status' => 'Available',
                'expected_return_date' => null,
                'upcoming_reservation' => null,
                'chassis_number' => '00000000000000000'
            ],
            [
                'node_id' => '0-7',
                'car_name' => 'Range Rover',
                'seats' => 5,
                'gear' => 'Automatic',
                'price_daily' => 900,
                'price_weekly' => 5000,
                'price_monthly' => 19000,
                'car_picture' => 'front/img/model.png',
                'doors' => 5,
                'description' => 'The 2024 Range Rover Vogue V6 seats 5 passengers in a luxurious, spacious interior. It is powered by a refined 3.0-liter V6 engine, delivering smooth performance and a perfect balance of power and efficiency. Known for its premium craftsmanship, the Vogue offers high-quality materials, advanced technology, and a quiet, comfortable ride. Features include a large touchscreen infotainment system, Apple CarPlay, Android Auto, and a suite of driver-assistance technologies. With its elegant design and off-road capability, the Range Rover Vogue combines luxury and ruggedness for an exceptional driving experience.',
                'created_at' => now(),
                'updated_at' => now(),
                'plate_number' => '700000',
                'make' => 'Land Rover',
                'model' => 'Vogue V6',
                'year' => 2024,
                'color' => 'Silver',
                'categories' => 'Sedan',
                'status' => 'Available',
                'expected_return_date' => null,
                'upcoming_reservation' => null,
                'chassis_number' => '00000000000000000'
            ],
            [
                'node_id' => '0-8',
                'car_name' => 'Nissan',
                'seats' => 5,
                'gear' => 'Automatic',
                'price_daily' => 80,
                'price_weekly' => 470,
                'price_monthly' => 1700,
                'car_picture' => 'front/img/model.png',
                'doors' => 5,
                'description' => 'The 2021 Nissan Versa seats 5 passengers. Its a compact sedan known for its affordability, fuel efficiency, and modern features. Powered by a 1.6-liter 4-cylinder engine, it offers a comfortable ride with good fuel economy. The Versa comes with advanced safety features like automatic emergency braking, lane departure warning, and a rearview camera. Inside, it includes a 7-inch touchscreen infotainment system with Apple CarPlay and Android Auto available on higher trims, making it a practical and budget-friendly option for daily driving',
                'created_at' => now(),
                'updated_at' => now(),
                'plate_number' => '800000',
                'make' => 'Nissan',
                'model' => 'Versa',
                'year' => 2021,
                'color' => 'Silver',
                'categories' => 'Sedan',
                'status' => 'Available',
                'expected_return_date' => null,
                'upcoming_reservation' => null,
                'chassis_number' => '00000000000000000'
            ],
            [
                'node_id' => '0-9',
                'car_name' => 'Chevrolet',
                'seats' => 5,
                'gear' => 'Automatic',
                'price_daily' => 130,
                'price_weekly' => 750,
                'price_monthly' => 2800,
                'car_picture' => 'front/img/model.png',
                'doors' => 5,
                'description' => 'The 2021 Nissan Versa seats 5 passengers. Its a compact sedan known for its affordability, fuel efficiency, and modern features. Powered by a 1.6-liter 4-cylinder engine, it offers a comfortable ride with good fuel economy. The Versa comes with advanced safety features like automatic emergency braking, lane departure warning, and a rearview camera. Inside, it includes a 7-inch touchscreen infotainment system with Apple CarPlay and Android Auto available on higher trims, making it a practical and budget-friendly option for daily driving',
                'created_at' => now(),
                'updated_at' => now(),
                'plate_number' => '900000',
                'make' => 'Chevrolet',
                'model' => 'Malibu',
                'year' => 2023,
                'color' => 'Silver',
                'categories' => 'Sedan',
                'status' => 'Available',
                'expected_return_date' => null,
                'upcoming_reservation' => null,
                'chassis_number' => '00000000000000000'
            ],
        ];

        DB::table('cars')->insert($cars);
    }
}